### ISSUE TITLE
A prior work with exactly same approach?

### ISSUE THREAD

**Issue by sylee0124** [lsj2408/Gaunt-Tensor-Product#2]
This paper [1] seems to propose **exactly the same computation method** for spherical harmonics product as this work. Can you give some comments about this paper?

[1] Xin, Hanggao, et al. "Fast and accurate spherical harmonics products." ACM Trans. Graph. 40.6 (2021): 280-1.
(https://dl.acm.org/doi/abs/10.1145/3478513.3480563) by @111116

**Comment by lsj2408** [comment]
Thank you for pointing this out. I would like to clarify here:

- **The contributions of our work**: as mentioned in our paper, our main contribution in this work is the new perspective on tensor products of irreps, which is novel and original to the machine learning community. The whole Section 3.1 elaborates on how to establish the connection between tensor products of irreps and integrals of products of spherical harmonics. Our establishment and derivation are based on a series of rigorous deductions with many efforts on building a solid mathematical foundation including group theory and quantum mechanics (please refer to Appendix A.1-A.7, page 16-28), which is not straightforward and trivial to obtain. Without these efforts, we cannot establish such connections, let alone the efficient algorithm. In the context of equivariant machine learning, this derivation presents significance to refresh the understanding of basic equivariant operations. 

- **The similarities of the efficient algorithms between our work and the mentioned work**: firstly, we would like to apologize that we did not cite this work in our submission, which is unintentional and due to the gap between these two communities. We will update the arXiv version of our paper asap by adding a discussion paragraph to carefully discuss the mentioned work and our work. On the other hand, we also would like to clarify the similarity: after we figure out the relation between the tensor product of irreps and integrals of the product of three spherical harmonics, it is rather natural to connect it with products of spherical functions. Moreover, there exist classical results for efficient computation of products of spherical functions, i.e., Convolution Theorem and FFT, which involve elementary knowledge that can be learned in several undergraduate classes: (1) change of basis, which can be learned in algebra and signal processing and is used in both paper to connect spherical harmonics and Fourier basis; (2) FFT, which is commonly taught in signal processing and numerical computation classes and is used for acceleration. Due to the basicness of these mathematical tools, both works follow the standard way to formalize and present, which leads to similarity.

- **The implementation**: it is noteworthy that, as a work for the equivariant machine learning community, it is not enough to simply propose an approach just for the tensor product operation. What we really care about is the various design paradigms of equivariant operations, which are built upon tensor products. In Section 3.3, we categorize these paradigms into three classes in terms of their different characteristics and applied range. For each class of equivariant operations, we carefully specialize our approach by combining their properties and considering the restrictions. For example, for the equivariant convolution, we figure out that we can further leverage eSCN/EquiformerV2's findings to achieve further acceleration; for the equivariant many-body interactions, a divide-and-conquer approach is natural, which is also generally taught in various CS courses and projects. There also exist different instantiation strategies in modern equivariant networks when applying these classes of operations, please refer to the Discussion paragraph in Section 3.3 and Appendix C. Simply proposing the efficient approach for tensor products is not feasible to these mentioned points. Without these additional efforts and contributions, the efficient algorithm is not practical to be used for the equivariant machine learning community,  which cannot be omitted.

Lastly, I would also like to apologize for the delayed responses and updates of the GitHub repo, which indeed somehow led to the misunderstanding. The notification email of the issue got buried among a flood of other GitHub notification emails, which made me omit it. We hope our clarifications here can address the concerns, and we will quickly update the arXiv version of our paper and the implementation code of Gaunt Tensor Product.
